name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Triggers the action only on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'poised-artwork-435918-s3'
          version: '>= 416.0.0'

      - name: Authenticate Docker with Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/poised-artwork-435918-s3/movie-streaming-app .
          docker push gcr.io/poised-artwork-435918-s3/movie-streaming-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy movie-streaming-app \
            --image gcr.io/poised-artwork-435918-s3/movie-streaming-app \
            --platform managed \
            --region asia-south2 \
            --allow-unauthenticated \
            --update-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --timeout=300  # Extend timeout for startup

      - name: Verify Deployment
        run: |
          curl https://movie-streaming-app-144879262315.asia-south2.run.app || echo "Deployment failed"
